-- Taskia — PostgreSQL
-- Las tablas se crean en el schema de PG_SCHEMA (por defecto "taskia"),
-- no en public. migrate.mjs hace CREATE SCHEMA + SET search_path antes de esto.
-- Instantes en timestamptz. Fechas de vencimiento en date.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_roles_code UNIQUE (code),
  CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);

CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_courses_user_name UNIQUE (user_id, name),
  CONSTRAINT uq_courses_id_user UNIQUE (id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_courses_user_id ON courses (user_id);

CREATE TABLE IF NOT EXISTS difficulties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_difficulties_code UNIQUE (code),
  CONSTRAINT uq_difficulties_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  difficulty_id BIGINT NOT NULL REFERENCES difficulties (id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  task_kind TEXT NOT NULL DEFAULT 'daily' CHECK (task_kind IN ('daily', 'project')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'studying', 'done')),
  board_order INT NOT NULL DEFAULT 0,
  study_passed BOOLEAN NOT NULL DEFAULT FALSE,
  uses_board BOOLEAN NOT NULL DEFAULT FALSE,
  study_mode_chosen BOOLEAN NOT NULL DEFAULT FALSE,
  due_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_tasks_course_owner
    FOREIGN KEY (course_id, user_id) REFERENCES courses (id, user_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_course_id ON tasks (course_id);
CREATE INDEX IF NOT EXISTS idx_tasks_difficulty_id ON tasks (difficulty_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_task_kind ON tasks (task_kind);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks (due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks (created_at);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status_order ON tasks (user_id, status, board_order);

CREATE TABLE IF NOT EXISTS study_sessions (
  task_id BIGINT PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
  tutor_phase TEXT NOT NULL DEFAULT 'understanding'
    CHECK (tutor_phase IN ('understanding', 'practicing', 'reviewing')),
  topic_summary TEXT NOT NULL,
  context_summary TEXT NOT NULL,
  hints_level INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant')),
  content TEXT NOT NULL,
  from_voice BOOLEAN NOT NULL DEFAULT FALSE,
  reply_latency_seconds INT NULL,
  is_pause BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_messages_task_created ON study_messages (task_id, created_at);

CREATE TABLE IF NOT EXISTS study_boards (
  task_id BIGINT PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
  board_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_study_memory (
  user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  memory_summary TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_worlds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL,
  description TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_worlds_id_user UNIQUE (id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_study_worlds_user ON study_worlds (user_id);
CREATE INDEX IF NOT EXISTS idx_study_worlds_user_active
  ON study_worlds (user_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS study_world_courses (
  world_id BIGINT NOT NULL REFERENCES study_worlds (id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  user_id BIGINT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (world_id, course_id),
  CONSTRAINT fk_study_world_courses_world_owner
    FOREIGN KEY (world_id, user_id) REFERENCES study_worlds (id, user_id) ON DELETE CASCADE,
  CONSTRAINT fk_study_world_courses_course_owner
    FOREIGN KEY (course_id, user_id) REFERENCES courses (id, user_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_study_world_courses_course ON study_world_courses (course_id);
CREATE INDEX IF NOT EXISTS idx_study_world_courses_world_active
  ON study_world_courses (world_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS study_missions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id BIGINT NOT NULL REFERENCES study_worlds (id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'studying', 'mastered')),
  uses_board BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  source_mission_id BIGINT NULL REFERENCES study_missions (id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_missions_id_world UNIQUE (id, world_id),
  CONSTRAINT fk_study_missions_world_course
    FOREIGN KEY (world_id, course_id) REFERENCES study_world_courses (world_id, course_id)
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_study_missions_world_course ON study_missions (world_id, course_id);
CREATE INDEX IF NOT EXISTS idx_study_missions_status ON study_missions (status);
CREATE INDEX IF NOT EXISTS idx_study_missions_source ON study_missions (source_mission_id);
CREATE INDEX IF NOT EXISTS idx_study_missions_world_course_active
  ON study_missions (world_id, course_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS study_mission_sessions (
  mission_id BIGINT PRIMARY KEY REFERENCES study_missions (id) ON DELETE CASCADE,
  tutor_phase TEXT NOT NULL DEFAULT 'understanding'
    CHECK (tutor_phase IN ('understanding', 'practicing', 'reviewing')),
  topic_summary TEXT NOT NULL,
  context_summary TEXT NOT NULL,
  notebook_context TEXT NOT NULL DEFAULT '',
  hints_level INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_mission_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id BIGINT NOT NULL REFERENCES study_missions (id) ON DELETE CASCADE,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant')),
  content TEXT NOT NULL,
  from_voice BOOLEAN NOT NULL DEFAULT FALSE,
  reply_latency_seconds INT NULL,
  is_pause BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_mission_messages_mission
  ON study_mission_messages (mission_id, id);

CREATE TABLE IF NOT EXISTS study_mission_boards (
  mission_id BIGINT PRIMARY KEY REFERENCES study_missions (id) ON DELETE CASCADE,
  board_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  world_id BIGINT NOT NULL REFERENCES study_worlds (id) ON DELETE CASCADE,
  scope TEXT NOT NULL,
  mission_id BIGINT NULL REFERENCES study_missions (id) ON DELETE SET NULL,
  course_id BIGINT NULL REFERENCES courses (id) ON DELETE SET NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('warm', 'quest', 'boss')),
  question_count INT NOT NULL,
  status TEXT NOT NULL DEFAULT 'in_progress'
    CHECK (status IN ('in_progress', 'completed', 'abandoned')),
  score SMALLINT NULL CHECK (score IS NULL OR (score >= 0 AND score <= 100)),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_study_challenges_scope CHECK (
    (scope = 'mission' AND mission_id IS NOT NULL)
    OR (scope = 'course' AND course_id IS NOT NULL AND mission_id IS NULL)
    OR (scope = 'world' AND mission_id IS NULL AND course_id IS NULL)
  ),
  CONSTRAINT fk_study_challenges_world_owner
    FOREIGN KEY (world_id, user_id) REFERENCES study_worlds (id, user_id) ON DELETE CASCADE,
  CONSTRAINT fk_study_challenges_mission_world
    FOREIGN KEY (mission_id, world_id) REFERENCES study_missions (id, world_id)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_study_challenges_world_course
    FOREIGN KEY (world_id, course_id) REFERENCES study_world_courses (world_id, course_id)
    DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS idx_study_challenges_user ON study_challenges (user_id, started_at);
CREATE INDEX IF NOT EXISTS idx_study_challenges_world ON study_challenges (world_id);
CREATE INDEX IF NOT EXISTS idx_study_challenges_mission ON study_challenges (mission_id);
CREATE INDEX IF NOT EXISTS idx_study_challenges_course ON study_challenges (course_id);

CREATE TABLE IF NOT EXISTS study_challenge_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id BIGINT NOT NULL REFERENCES study_challenges (id) ON DELETE CASCADE,
  mission_id BIGINT NULL REFERENCES study_missions (id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  kind TEXT NOT NULL
    CHECK (kind IN ('multiple_choice', 'short_text', 'fill_blank', 'board_prompt')),
  prompt TEXT NOT NULL,
  options_json JSONB NULL,
  answer_key TEXT NOT NULL,
  requires_board BOOLEAN NOT NULL DEFAULT FALSE,
  prompt_draw_ops JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_challenge_questions_challenge
  ON study_challenge_questions (challenge_id, sort_order);

CREATE TABLE IF NOT EXISTS study_challenge_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES study_challenge_questions (id) ON DELETE CASCADE,
  user_answer TEXT NULL,
  board_json TEXT NULL,
  is_correct BOOLEAN NULL,
  answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_challenge_answers_question UNIQUE (question_id)
);

CREATE TABLE IF NOT EXISTS study_challenge_presets (
  scope TEXT NOT NULL CHECK (scope IN ('mission', 'course', 'world')),
  difficulty TEXT NOT NULL CHECK (difficulty IN ('warm', 'quest', 'boss')),
  question_count INT NOT NULL,
  label VARCHAR(40) NOT NULL,
  PRIMARY KEY (scope, difficulty)
);

CREATE TABLE IF NOT EXISTS parent_student_links (
  parent_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (parent_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_parent_student_links_student
  ON parent_student_links (student_id) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_parent_student_links_parent
  ON parent_student_links (parent_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS parent_notify_prefs (
  parent_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  whatsapp_e164 TEXT NULL,
  notify_task_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_task_study_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_mission_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_course_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_world_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_challenge_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_inactivity BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_daily_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  summary_date DATE NOT NULL,
  summary_text TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_student_daily_summaries UNIQUE (student_id, summary_date)
);
CREATE INDEX IF NOT EXISTS idx_student_daily_summaries_student_date
  ON student_daily_summaries (student_id, summary_date DESC)
  WHERE is_active;

CREATE TABLE IF NOT EXISTS parent_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant')),
  content TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_parent_chat_messages_pair
  ON parent_chat_messages (parent_id, student_id, id)
  WHERE is_active;

CREATE TABLE IF NOT EXISTS llm_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN (
    'task_tutor',
    'mission_tutor',
    'transcribe',
    'challenge_generate',
    'challenge_grade',
    'parent_tutor'
  )),
  model VARCHAR(80) NOT NULL,
  prompt_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  total_tokens INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_llm_usage_user_created ON llm_usage (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_llm_usage_kind_created ON llm_usage (kind, created_at);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_tasks_updated_at ON tasks;
CREATE TRIGGER trg_tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_sessions_updated_at ON study_sessions;
CREATE TRIGGER trg_study_sessions_updated_at
  BEFORE UPDATE ON study_sessions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_boards_updated_at ON study_boards;
CREATE TRIGGER trg_study_boards_updated_at
  BEFORE UPDATE ON study_boards
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_user_study_memory_updated_at ON user_study_memory;
CREATE TRIGGER trg_user_study_memory_updated_at
  BEFORE UPDATE ON user_study_memory
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_worlds_updated_at ON study_worlds;
CREATE TRIGGER trg_study_worlds_updated_at
  BEFORE UPDATE ON study_worlds
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_missions_updated_at ON study_missions;
CREATE TRIGGER trg_study_missions_updated_at
  BEFORE UPDATE ON study_missions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_mission_sessions_updated_at ON study_mission_sessions;
CREATE TRIGGER trg_study_mission_sessions_updated_at
  BEFORE UPDATE ON study_mission_sessions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_mission_boards_updated_at ON study_mission_boards;
CREATE TRIGGER trg_study_mission_boards_updated_at
  BEFORE UPDATE ON study_mission_boards
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_parent_student_links_updated_at ON parent_student_links;
CREATE TRIGGER trg_parent_student_links_updated_at
  BEFORE UPDATE ON parent_student_links
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_parent_notify_prefs_updated_at ON parent_notify_prefs;
CREATE TRIGGER trg_parent_notify_prefs_updated_at
  BEFORE UPDATE ON parent_notify_prefs
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_student_daily_summaries_updated_at ON student_daily_summaries;
CREATE TRIGGER trg_student_daily_summaries_updated_at
  BEFORE UPDATE ON student_daily_summaries
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

-- Vigila, al cerrar la transacción, que ninguna misión activa
-- cuelgue de un mundo o de un vínculo mundo-materia inactivo.
CREATE OR REPLACE FUNCTION assert_active_mission_link()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'study_missions' THEN
    IF NEW.is_active AND NOT EXISTS (
      SELECT 1
      FROM study_worlds w
      INNER JOIN study_world_courses wc
        ON wc.world_id = w.id AND wc.course_id = NEW.course_id
      WHERE w.id = NEW.world_id
        AND w.is_active
        AND wc.is_active
    ) THEN
      RAISE EXCEPTION 'Hay una misión activa en un mundo o materia inactiva';
    END IF;
  ELSIF TG_TABLE_NAME = 'study_worlds' THEN
    IF NOT NEW.is_active AND EXISTS (
      SELECT 1 FROM study_missions m
      WHERE m.world_id = NEW.id AND m.is_active
    ) THEN
      RAISE EXCEPTION 'Hay una misión activa en un mundo o materia inactiva';
    END IF;
  ELSIF TG_TABLE_NAME = 'study_world_courses' THEN
    IF NOT NEW.is_active AND EXISTS (
      SELECT 1 FROM study_missions m
      WHERE m.world_id = NEW.world_id
        AND m.course_id = NEW.course_id
        AND m.is_active
    ) THEN
      RAISE EXCEPTION 'Hay una misión activa en un mundo o materia inactiva';
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_active_mission_on_missions ON study_missions;
CREATE CONSTRAINT TRIGGER trg_active_mission_on_missions
  AFTER INSERT OR UPDATE ON study_missions
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE PROCEDURE assert_active_mission_link();

DROP TRIGGER IF EXISTS trg_active_mission_on_worlds ON study_worlds;
CREATE CONSTRAINT TRIGGER trg_active_mission_on_worlds
  AFTER INSERT OR UPDATE ON study_worlds
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE PROCEDURE assert_active_mission_link();

DROP TRIGGER IF EXISTS trg_active_mission_on_world_courses ON study_world_courses;
CREATE CONSTRAINT TRIGGER trg_active_mission_on_world_courses
  AFTER INSERT OR UPDATE ON study_world_courses
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE PROCEDURE assert_active_mission_link();

INSERT INTO roles (code, name) VALUES
  ('user', 'Explorador'),
  ('admin', 'Administrador'),
  ('parent', 'Guardián')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO difficulties (code, name, sort_order) VALUES
  ('low', 'Bajo', 1),
  ('medium', 'Medio', 2),
  ('high', 'Alto', 3)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order;

INSERT INTO study_challenge_presets (scope, difficulty, question_count, label) VALUES
  ('mission', 'warm', 5, 'Calentamiento'),
  ('mission', 'quest', 8, 'Aventura'),
  ('mission', 'boss', 10, 'Jefe final'),
  ('course', 'warm', 10, 'Calentamiento'),
  ('course', 'quest', 15, 'Aventura'),
  ('course', 'boss', 20, 'Jefe final'),
  ('world', 'warm', 20, 'Calentamiento'),
  ('world', 'quest', 40, 'Aventura'),
  ('world', 'boss', 80, 'Jefe final')
ON CONFLICT (scope, difficulty) DO UPDATE SET
  question_count = EXCLUDED.question_count,
  label = EXCLUDED.label;
