/**
 * Foto inicial del schema Taskia: tablas, triggers, catálogo y semillas demo.
 *
 * No editar este archivo para un cambio posterior. El siguiente cambio es un
 * archivo nuevo NNN_motivo.ts que solo agrega o quita lo que falta.
 *
 * Una base que ya tenía el esquema (migraciones 001–011) no vuelve a correr esto.
 */
import bcrypt from 'bcryptjs'
import type { Client } from 'pg'
import { runScript } from '../run-script.js'

const SCHEMA = `
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_roles_code UNIQUE (code),
  CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  level INT NOT NULL DEFAULT 1,
  xp_total BIGINT NOT NULL DEFAULT 0,
  avatar_kind TEXT NOT NULL DEFAULT 'preset',
  avatar_preset_id VARCHAR(40) NULL,
  avatar_file VARCHAR(120) NULL,
  frame_id VARCHAR(40) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT ck_users_level CHECK (level >= 1),
  CONSTRAINT ck_users_xp_total CHECK (xp_total >= 0),
  CONSTRAINT ck_users_avatar_kind CHECK (avatar_kind IN ('preset', 'upload'))
);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);
CREATE INDEX IF NOT EXISTS idx_users_level_xp ON users (level DESC, xp_total DESC);

CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_courses_user_name UNIQUE (user_id, name),
  CONSTRAINT uq_courses_id_user UNIQUE (id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_courses_user_id ON courses (user_id);

CREATE TABLE IF NOT EXISTS difficulties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_difficulties_code UNIQUE (code),
  CONSTRAINT uq_difficulties_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  difficulty_id BIGINT NOT NULL REFERENCES difficulties (id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  task_kind TEXT NOT NULL DEFAULT 'daily' CHECK (task_kind IN ('daily', 'project')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'studying', 'done')),
  board_order INT NOT NULL DEFAULT 0,
  study_passed BOOLEAN NOT NULL DEFAULT FALSE,
  uses_board BOOLEAN NOT NULL DEFAULT FALSE,
  study_mode_chosen BOOLEAN NOT NULL DEFAULT FALSE,
  due_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_tasks_course_owner
    FOREIGN KEY (course_id, user_id) REFERENCES courses (id, user_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_course_id ON tasks (course_id);
CREATE INDEX IF NOT EXISTS idx_tasks_difficulty_id ON tasks (difficulty_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_task_kind ON tasks (task_kind);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks (due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks (created_at);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status_order ON tasks (user_id, status, board_order);

CREATE TABLE IF NOT EXISTS study_sessions (
  task_id BIGINT PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
  tutor_phase TEXT NOT NULL DEFAULT 'understanding'
    CHECK (tutor_phase IN ('understanding', 'practicing', 'reviewing')),
  topic_summary TEXT NOT NULL,
  context_summary TEXT NOT NULL,
  hints_level INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant')),
  content TEXT NOT NULL,
  from_voice BOOLEAN NOT NULL DEFAULT FALSE,
  reply_latency_seconds INT NULL,
  is_pause BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_messages_task_created ON study_messages (task_id, created_at);

CREATE TABLE IF NOT EXISTS study_boards (
  task_id BIGINT PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
  board_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_study_memory (
  user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  memory_summary TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_worlds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL,
  description TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_worlds_id_user UNIQUE (id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_study_worlds_user ON study_worlds (user_id);
CREATE INDEX IF NOT EXISTS idx_study_worlds_user_active
  ON study_worlds (user_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS study_world_courses (
  world_id BIGINT NOT NULL REFERENCES study_worlds (id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  user_id BIGINT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (world_id, course_id),
  CONSTRAINT fk_study_world_courses_world_owner
    FOREIGN KEY (world_id, user_id) REFERENCES study_worlds (id, user_id) ON DELETE CASCADE,
  CONSTRAINT fk_study_world_courses_course_owner
    FOREIGN KEY (course_id, user_id) REFERENCES courses (id, user_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_study_world_courses_course ON study_world_courses (course_id);
CREATE INDEX IF NOT EXISTS idx_study_world_courses_world_active
  ON study_world_courses (world_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS study_missions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id BIGINT NOT NULL REFERENCES study_worlds (id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses (id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'studying', 'mastered')),
  uses_board BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  source_mission_id BIGINT NULL REFERENCES study_missions (id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_missions_id_world UNIQUE (id, world_id),
  CONSTRAINT fk_study_missions_world_course
    FOREIGN KEY (world_id, course_id) REFERENCES study_world_courses (world_id, course_id)
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_study_missions_world_course ON study_missions (world_id, course_id);
CREATE INDEX IF NOT EXISTS idx_study_missions_status ON study_missions (status);
CREATE INDEX IF NOT EXISTS idx_study_missions_source ON study_missions (source_mission_id);
CREATE INDEX IF NOT EXISTS idx_study_missions_world_course_active
  ON study_missions (world_id, course_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS study_mission_sessions (
  mission_id BIGINT PRIMARY KEY REFERENCES study_missions (id) ON DELETE CASCADE,
  tutor_phase TEXT NOT NULL DEFAULT 'understanding'
    CHECK (tutor_phase IN ('understanding', 'practicing', 'reviewing')),
  topic_summary TEXT NOT NULL,
  context_summary TEXT NOT NULL,
  notebook_context TEXT NOT NULL DEFAULT '',
  hints_level INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_mission_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id BIGINT NOT NULL REFERENCES study_missions (id) ON DELETE CASCADE,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant')),
  content TEXT NOT NULL,
  from_voice BOOLEAN NOT NULL DEFAULT FALSE,
  reply_latency_seconds INT NULL,
  is_pause BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_mission_messages_mission
  ON study_mission_messages (mission_id, id);

CREATE TABLE IF NOT EXISTS study_mission_boards (
  mission_id BIGINT PRIMARY KEY REFERENCES study_missions (id) ON DELETE CASCADE,
  board_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  world_id BIGINT NOT NULL REFERENCES study_worlds (id) ON DELETE CASCADE,
  scope TEXT NOT NULL,
  mission_id BIGINT NULL REFERENCES study_missions (id) ON DELETE SET NULL,
  course_id BIGINT NULL REFERENCES courses (id) ON DELETE SET NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('warm', 'quest', 'boss')),
  question_count INT NOT NULL,
  status TEXT NOT NULL DEFAULT 'in_progress'
    CHECK (status IN ('in_progress', 'completed', 'abandoned')),
  score SMALLINT NULL CHECK (score IS NULL OR (score >= 0 AND score <= 100)),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_study_challenges_scope CHECK (
    (scope = 'mission' AND mission_id IS NOT NULL)
    OR (scope = 'course' AND course_id IS NOT NULL AND mission_id IS NULL)
    OR (scope = 'world' AND mission_id IS NULL AND course_id IS NULL)
  ),
  CONSTRAINT fk_study_challenges_world_owner
    FOREIGN KEY (world_id, user_id) REFERENCES study_worlds (id, user_id) ON DELETE CASCADE,
  CONSTRAINT fk_study_challenges_mission_world
    FOREIGN KEY (mission_id, world_id) REFERENCES study_missions (id, world_id)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_study_challenges_world_course
    FOREIGN KEY (world_id, course_id) REFERENCES study_world_courses (world_id, course_id)
    DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS idx_study_challenges_user ON study_challenges (user_id, started_at);
CREATE INDEX IF NOT EXISTS idx_study_challenges_world ON study_challenges (world_id);
CREATE INDEX IF NOT EXISTS idx_study_challenges_mission ON study_challenges (mission_id);
CREATE INDEX IF NOT EXISTS idx_study_challenges_course ON study_challenges (course_id);

CREATE TABLE IF NOT EXISTS study_challenge_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id BIGINT NOT NULL REFERENCES study_challenges (id) ON DELETE CASCADE,
  mission_id BIGINT NULL REFERENCES study_missions (id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  kind TEXT NOT NULL
    CHECK (kind IN ('multiple_choice', 'short_text', 'fill_blank', 'board_prompt')),
  prompt TEXT NOT NULL,
  options_json JSONB NULL,
  answer_key TEXT NOT NULL,
  requires_board BOOLEAN NOT NULL DEFAULT FALSE,
  prompt_draw_ops JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_challenge_questions_challenge
  ON study_challenge_questions (challenge_id, sort_order);

CREATE TABLE IF NOT EXISTS study_challenge_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES study_challenge_questions (id) ON DELETE CASCADE,
  user_answer TEXT NULL,
  board_json TEXT NULL,
  is_correct BOOLEAN NULL,
  answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_challenge_answers_question UNIQUE (question_id)
);

CREATE TABLE IF NOT EXISTS study_challenge_presets (
  scope TEXT NOT NULL CHECK (scope IN ('mission', 'course', 'world')),
  difficulty TEXT NOT NULL CHECK (difficulty IN ('warm', 'quest', 'boss')),
  question_count INT NOT NULL,
  label VARCHAR(40) NOT NULL,
  PRIMARY KEY (scope, difficulty)
);

CREATE TABLE IF NOT EXISTS parent_student_links (
  parent_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (parent_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_parent_student_links_student
  ON parent_student_links (student_id) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_parent_student_links_parent
  ON parent_student_links (parent_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS parent_notify_prefs (
  parent_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  whatsapp_e164 TEXT NULL,
  notify_task_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_task_study_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_mission_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_course_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_world_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_challenge_done BOOLEAN NOT NULL DEFAULT TRUE,
  notify_inactivity BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_daily_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  summary_date DATE NOT NULL,
  summary_text TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_student_daily_summaries UNIQUE (student_id, summary_date)
);
CREATE INDEX IF NOT EXISTS idx_student_daily_summaries_student_date
  ON student_daily_summaries (student_id, summary_date DESC)
  WHERE is_active;

CREATE TABLE IF NOT EXISTS parent_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant')),
  content TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_parent_chat_messages_pair
  ON parent_chat_messages (parent_id, student_id, id)
  WHERE is_active;

CREATE TABLE IF NOT EXISTS llm_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  model VARCHAR(80) NOT NULL,
  prompt_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  total_tokens INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT llm_usage_kind_check CHECK (kind IN (
    'task_tutor',
    'mission_tutor',
    'transcribe',
    'challenge_generate',
    'challenge_grade',
    'parent_tutor',
    'planet_generate'
  ))
);
CREATE INDEX IF NOT EXISTS idx_llm_usage_user_created ON llm_usage (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_llm_usage_kind_created ON llm_usage (kind, created_at);

CREATE TABLE IF NOT EXISTS xp_awards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_id BIGINT NOT NULL,
  amount INT NOT NULL,
  effort_score INT NULL,
  reason VARCHAR(200) NULL,
  week_start DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_xp_awards_source_type CHECK (
    source_type IN ('task_done_simple', 'task_study', 'mission', 'challenge')
  ),
  CONSTRAINT ck_xp_awards_amount CHECK (amount > 0),
  CONSTRAINT ck_xp_awards_effort_score CHECK (
    effort_score IS NULL OR (effort_score >= 1 AND effort_score <= 100)
  ),
  CONSTRAINT uq_xp_awards_user_source UNIQUE (user_id, source_type, source_id)
);
CREATE INDEX IF NOT EXISTS idx_xp_awards_user_week ON xp_awards (user_id, week_start);
CREATE INDEX IF NOT EXISTS idx_xp_awards_week ON xp_awards (week_start);

CREATE TABLE IF NOT EXISTS troops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  planet_style_id VARCHAR(40) NOT NULL DEFAULT 'rocky_blue',
  planet_seed INT NOT NULL DEFAULT 0,
  planet_params JSONB NULL,
  planet_config JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_troops_active ON troops (id) WHERE is_active;

CREATE TABLE IF NOT EXISTS troop_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  troop_id BIGINT NOT NULL REFERENCES troops (id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  left_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_troop_members_role CHECK (role IN ('captain', 'copilot', 'member')),
  CONSTRAINT uq_troop_members_troop_user UNIQUE (troop_id, user_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_members_user_active
  ON troop_members (user_id) WHERE left_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_members_captain_active
  ON troop_members (troop_id)
  WHERE role = 'captain' AND left_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_members_copilot_active
  ON troop_members (troop_id)
  WHERE role = 'copilot' AND left_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_troop_members_troop_active
  ON troop_members (troop_id) WHERE left_at IS NULL;

CREATE TABLE IF NOT EXISTS troop_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  troop_id BIGINT NOT NULL REFERENCES troops (id) ON DELETE CASCADE,
  from_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  to_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  direction TEXT NOT NULL DEFAULT 'invite',
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  responded_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_troop_invites_direction CHECK (direction IN ('invite', 'request')),
  CONSTRAINT ck_troop_invites_status CHECK (
    status IN ('pending', 'accepted', 'rejected', 'cancelled')
  ),
  CONSTRAINT ck_troop_invites_not_self CHECK (from_user_id <> to_user_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_invites_pending_invite
  ON troop_invites (troop_id, to_user_id)
  WHERE status = 'pending' AND direction = 'invite';
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_invites_pending_request
  ON troop_invites (troop_id, from_user_id)
  WHERE status = 'pending' AND direction = 'request';
CREATE INDEX IF NOT EXISTS idx_troop_invites_troop_requests
  ON troop_invites (troop_id)
  WHERE status = 'pending' AND direction = 'request';
CREATE INDEX IF NOT EXISTS idx_troop_invites_to_pending
  ON troop_invites (to_user_id) WHERE status = 'pending';

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_tasks_updated_at ON tasks;
CREATE TRIGGER trg_tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_sessions_updated_at ON study_sessions;
CREATE TRIGGER trg_study_sessions_updated_at
  BEFORE UPDATE ON study_sessions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_boards_updated_at ON study_boards;
CREATE TRIGGER trg_study_boards_updated_at
  BEFORE UPDATE ON study_boards
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_user_study_memory_updated_at ON user_study_memory;
CREATE TRIGGER trg_user_study_memory_updated_at
  BEFORE UPDATE ON user_study_memory
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_worlds_updated_at ON study_worlds;
CREATE TRIGGER trg_study_worlds_updated_at
  BEFORE UPDATE ON study_worlds
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_missions_updated_at ON study_missions;
CREATE TRIGGER trg_study_missions_updated_at
  BEFORE UPDATE ON study_missions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_mission_sessions_updated_at ON study_mission_sessions;
CREATE TRIGGER trg_study_mission_sessions_updated_at
  BEFORE UPDATE ON study_mission_sessions
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_study_mission_boards_updated_at ON study_mission_boards;
CREATE TRIGGER trg_study_mission_boards_updated_at
  BEFORE UPDATE ON study_mission_boards
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_parent_student_links_updated_at ON parent_student_links;
CREATE TRIGGER trg_parent_student_links_updated_at
  BEFORE UPDATE ON parent_student_links
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_parent_notify_prefs_updated_at ON parent_notify_prefs;
CREATE TRIGGER trg_parent_notify_prefs_updated_at
  BEFORE UPDATE ON parent_notify_prefs
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_student_daily_summaries_updated_at ON student_daily_summaries;
CREATE TRIGGER trg_student_daily_summaries_updated_at
  BEFORE UPDATE ON student_daily_summaries
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

DROP TRIGGER IF EXISTS trg_troops_updated_at ON troops;
CREATE TRIGGER trg_troops_updated_at
  BEFORE UPDATE ON troops
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

CREATE OR REPLACE FUNCTION assert_active_mission_link()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'study_missions' THEN
    IF NEW.is_active AND NOT EXISTS (
      SELECT 1
      FROM study_worlds w
      INNER JOIN study_world_courses wc
        ON wc.world_id = w.id AND wc.course_id = NEW.course_id
      WHERE w.id = NEW.world_id
        AND w.is_active
        AND wc.is_active
    ) THEN
      RAISE EXCEPTION 'Hay una misión activa en un mundo o materia inactiva';
    END IF;
  ELSIF TG_TABLE_NAME = 'study_worlds' THEN
    IF NOT NEW.is_active AND EXISTS (
      SELECT 1 FROM study_missions m
      WHERE m.world_id = NEW.id AND m.is_active
    ) THEN
      RAISE EXCEPTION 'Hay una misión activa en un mundo o materia inactiva';
    END IF;
  ELSIF TG_TABLE_NAME = 'study_world_courses' THEN
    IF NOT NEW.is_active AND EXISTS (
      SELECT 1 FROM study_missions m
      WHERE m.world_id = NEW.world_id
        AND m.course_id = NEW.course_id
        AND m.is_active
    ) THEN
      RAISE EXCEPTION 'Hay una misión activa en un mundo o materia inactiva';
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_active_mission_on_missions ON study_missions;
CREATE CONSTRAINT TRIGGER trg_active_mission_on_missions
  AFTER INSERT OR UPDATE ON study_missions
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE PROCEDURE assert_active_mission_link();

DROP TRIGGER IF EXISTS trg_active_mission_on_worlds ON study_worlds;
CREATE CONSTRAINT TRIGGER trg_active_mission_on_worlds
  AFTER INSERT OR UPDATE ON study_worlds
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE PROCEDURE assert_active_mission_link();

DROP TRIGGER IF EXISTS trg_active_mission_on_world_courses ON study_world_courses;
CREATE CONSTRAINT TRIGGER trg_active_mission_on_world_courses
  AFTER INSERT OR UPDATE ON study_world_courses
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE PROCEDURE assert_active_mission_link();

INSERT INTO roles (code, name) VALUES
  ('user', 'Explorador'),
  ('admin', 'Administrador'),
  ('parent', 'Guardián')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO difficulties (code, name, sort_order) VALUES
  ('low', 'Bajo', 1),
  ('medium', 'Medio', 2),
  ('high', 'Alto', 3)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order;

INSERT INTO study_challenge_presets (scope, difficulty, question_count, label) VALUES
  ('mission', 'warm', 5, 'Calentamiento'),
  ('mission', 'quest', 8, 'Aventura'),
  ('mission', 'boss', 10, 'Jefe final'),
  ('course', 'warm', 10, 'Calentamiento'),
  ('course', 'quest', 15, 'Aventura'),
  ('course', 'boss', 20, 'Jefe final'),
  ('world', 'warm', 20, 'Calentamiento'),
  ('world', 'quest', 40, 'Aventura'),
  ('world', 'boss', 80, 'Jefe final')
ON CONFLICT (scope, difficulty) DO UPDATE SET
  question_count = EXCLUDED.question_count,
  label = EXCLUDED.label;
`

const PRIMARY_COURSES = [
  'Matemática',
  'Comunicación',
  'Ciencia y Tecnología',
  'Personal Social',
  'Arte y Cultura',
  'Educación Física',
  'Inglés',
  'Religión',
]

const DEMO_PASSWORD = '123456'
const ANCHOR_TROOP = 'Los Veloces'

type Member = {
  username: string
  role: 'captain' | 'copilot' | 'member'
  level: number
  xpInto: number
  xpWeek: number
}

type TroopSeed = {
  name: string
  planet_style_id: string
  planet_seed: number
  members: Member[]
}

const TROOPS: TroopSeed[] = [
  {
    name: ANCHOR_TROOP,
    planet_style_id: 'rocky_blue',
    planet_seed: 1001,
    members: [
      { username: 'Seroven', role: 'captain', level: 4, xpInto: 320, xpWeek: 480 },
      { username: 'MateoR', role: 'copilot', level: 5, xpInto: 110, xpWeek: 620 },
      { username: 'LuciaV', role: 'member', level: 3, xpInto: 780, xpWeek: 210 },
      { username: 'DiegoP', role: 'member', level: 2, xpInto: 450, xpWeek: 95 },
      { username: 'SofiaM', role: 'member', level: 6, xpInto: 40, xpWeek: 710 },
      { username: 'LeoG', role: 'member', level: 1, xpInto: 180, xpWeek: 40 },
      { username: 'ValentinaC', role: 'member', level: 4, xpInto: 900, xpWeek: 350 },
      { username: 'NicolasH', role: 'member', level: 3, xpInto: 55, xpWeek: 160 },
    ],
  },
  {
    name: 'Estrellas del Norte',
    planet_style_id: 'neon_violet',
    planet_seed: 1002,
    members: [
      { username: 'CamilaT', role: 'captain', level: 7, xpInto: 220, xpWeek: 890 },
      { username: 'JoaquinB', role: 'copilot', level: 6, xpInto: 640, xpWeek: 540 },
      { username: 'IsabellaF', role: 'member', level: 5, xpInto: 300, xpWeek: 400 },
      { username: 'BenjaminL', role: 'member', level: 4, xpInto: 10, xpWeek: 280 },
      { username: 'MartinaS', role: 'member', level: 3, xpInto: 500, xpWeek: 190 },
      { username: 'SantiagoO', role: 'member', level: 2, xpInto: 870, xpWeek: 120 },
      { username: 'EmiliaR', role: 'member', level: 8, xpInto: 15, xpWeek: 950 },
      { username: 'ThiagoD', role: 'member', level: 1, xpInto: 60, xpWeek: 25 },
      { username: 'AntonellaP', role: 'member', level: 5, xpInto: 770, xpWeek: 330 },
    ],
  },
  {
    name: 'Guardianes del Saber',
    planet_style_id: 'forest_green',
    planet_seed: 1003,
    members: [
      { username: 'RenataA', role: 'captain', level: 9, xpInto: 400, xpWeek: 1020 },
      { username: 'LucasE', role: 'copilot', level: 7, xpInto: 50, xpWeek: 700 },
      { username: 'AmandaQ', role: 'member', level: 6, xpInto: 880, xpWeek: 460 },
      { username: 'FelipeN', role: 'member', level: 4, xpInto: 200, xpWeek: 250 },
      { username: 'CatalinaZ', role: 'member', level: 3, xpInto: 990, xpWeek: 180 },
      { username: 'AgustinM', role: 'member', level: 2, xpInto: 120, xpWeek: 75 },
      { username: 'PaulaI', role: 'member', level: 5, xpInto: 560, xpWeek: 390 },
      { username: 'MaximilianoV', role: 'member', level: 8, xpInto: 300, xpWeek: 810 },
      { username: 'JosefinaK', role: 'member', level: 1, xpInto: 420, xpWeek: 55 },
      { username: 'TomasW', role: 'member', level: 4, xpInto: 670, xpWeek: 300 },
    ],
  },
  {
    name: 'Rayos Azules',
    planet_style_id: 'ice_cyan',
    planet_seed: 1004,
    members: [
      { username: 'DanielaY', role: 'captain', level: 3, xpInto: 150, xpWeek: 200 },
      { username: 'GabrielX', role: 'copilot', level: 2, xpInto: 800, xpWeek: 140 },
      { username: 'FlorenciaJ', role: 'member', level: 1, xpInto: 30, xpWeek: 15 },
      { username: 'IgnacioU', role: 'member', level: 4, xpInto: 500, xpWeek: 270 },
      { username: 'ConstanzaB', role: 'member', level: 2, xpInto: 250, xpWeek: 90 },
      { username: 'RodrigoC', role: 'member', level: 5, xpInto: 10, xpWeek: 360 },
    ],
  },
  {
    name: 'Cometas del Sur',
    planet_style_id: 'lava_amber',
    planet_seed: 1005,
    members: [
      { username: 'ElenaD', role: 'captain', level: 6, xpInto: 450, xpWeek: 580 },
      { username: 'PabloF', role: 'copilot', level: 5, xpInto: 200, xpWeek: 440 },
      { username: 'JulietaG', role: 'member', level: 4, xpInto: 800, xpWeek: 310 },
      { username: 'AndresH', role: 'member', level: 3, xpInto: 100, xpWeek: 170 },
      { username: 'MarianaI', role: 'member', level: 7, xpInto: 900, xpWeek: 760 },
      { username: 'SebastianJ', role: 'member', level: 2, xpInto: 600, xpWeek: 110 },
      { username: 'CarlaK', role: 'member', level: 1, xpInto: 900, xpWeek: 80 },
    ],
  },
  {
    name: 'Pioneros',
    planet_style_id: 'rose_dust',
    planet_seed: 1006,
    members: [
      { username: 'BrunoL', role: 'captain', level: 2, xpInto: 50, xpWeek: 60 },
      { username: 'OliviaM', role: 'copilot', level: 1, xpInto: 700, xpWeek: 45 },
      { username: 'HugoN', role: 'member', level: 3, xpInto: 300, xpWeek: 130 },
      { username: 'IrisO', role: 'member', level: 1, xpInto: 10, xpWeek: 10 },
      { username: 'KevinP', role: 'member', level: 2, xpInto: 990, xpWeek: 100 },
    ],
  },
]

const GUARDIAN_BY_EXPLORER: Record<string, string> = {
  MateoR: 'RosaM',
  LuciaV: 'PedroV',
  DiegoP: 'AnaP',
  SofiaM: 'CarlosM',
  LeoG: 'MariaG',
  ValentinaC: 'JorgeC',
  NicolasH: 'LauraH',
  CamilaT: 'MartaT',
  JoaquinB: 'RicardoB',
  IsabellaF: 'ElenaF',
  BenjaminL: 'PatriciaL',
  MartinaS: 'HectorS',
  SantiagoO: 'GloriaO',
  EmiliaR: 'RaulR',
  ThiagoD: 'SilviaD',
  AntonellaP: 'FernandoP',
  RenataA: 'BeatrizA',
  LucasE: 'DiegoE',
  AmandaQ: 'NormaQ',
  FelipeN: 'OscarN',
  CatalinaZ: 'IreneZ',
  AgustinM: 'VictorM',
  PaulaI: 'CarmenI',
  MaximilianoV: 'SandraV',
  JosefinaK: 'AlbertoK',
  TomasW: 'MonicaW',
  DanielaY: 'LuisY',
  GabrielX: 'PilarX',
  FlorenciaJ: 'RamonJ',
  IgnacioU: 'TeresaU',
  ConstanzaB: 'ManuelB',
  RodrigoC: 'AliciaC',
  ElenaD: 'FranciscoD',
  PabloF: 'IsabelF',
  JulietaG: 'EduardoG',
  AndresH: 'CeciliaH',
  MarianaI: 'RobertoI',
  SebastianJ: 'AdrianaJ',
  CarlaK: 'MiguelK',
  BrunoL: 'SusanaL',
  OliviaM: 'AndresM',
  HugoN: 'ClaudiaN',
  IrisO: 'JoseO',
  KevinP: 'NataliaP',
}

function weekStartMondayLima(instant = new Date()) {
  const civil = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/Lima',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(instant)
  const [y, m, d] = civil.split('-').map(Number)
  const asUtc = Date.UTC(y, m - 1, d)
  const dow = new Date(asUtc).getUTCDay()
  const daysSinceMonday = dow === 0 ? 6 : dow - 1
  const monday = new Date(asUtc - daysSinceMonday * 86_400_000)
  return monday.toISOString().slice(0, 10)
}

async function roleId(client: Client, code: string) {
  const r = await client.query(`SELECT id FROM roles WHERE code = $1 LIMIT 1`, [code])
  const id = r.rows[0]?.id
  if (id == null) throw new Error(`Falta el rol ${code}`)
  return Number(id)
}

async function seedAdmin(client: Client) {
  const username = 'Sebastian'
  const email = 'sebastian@taskia.local'
  const existing = await client.query(
    `SELECT id FROM users WHERE username = $1 OR email = $2 LIMIT 1`,
    [username, email],
  )
  if (existing.rows.length > 0) {
    console.log(`  admin ${username} ya existe — sin cambios`)
    return
  }
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10)
  await client.query(
    `INSERT INTO users (username, email, password_hash, role_id, is_active)
     VALUES ($1, $2, $3, $4, TRUE)`,
    [username, email, passwordHash, await roleId(client, 'admin')],
  )
  console.log(`  admin creado: ${username} / ${DEMO_PASSWORD}`)
}

async function ensureUser(
  client: Client,
  username: string,
  email: string,
  roleCode: string,
  passwordHash: string,
  level: number | null,
  xpTotal: number | null,
) {
  const existing = await client.query(
    `SELECT id FROM users WHERE username = $1 OR email = $2 LIMIT 1`,
    [username, email],
  )
  if (existing.rows.length > 0) {
    const id = Number(existing.rows[0].id)
    if (roleCode === 'user' && level != null && xpTotal != null) {
      await client.query(`UPDATE users SET level = $1, xp_total = $2 WHERE id = $3`, [
        level,
        xpTotal,
        id,
      ])
    }
    return id
  }
  const inserted = await client.query(
    `INSERT INTO users (username, email, password_hash, role_id, is_active, level, xp_total)
     VALUES ($1, $2, $3, $4, TRUE, $5, $6)
     RETURNING id`,
    [username, email, passwordHash, await roleId(client, roleCode), level ?? 1, xpTotal ?? 0],
  )
  return Number(inserted.rows[0].id)
}

async function seedDemoUsers(client: Client) {
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10)
  const explorerId = await ensureUser(
    client,
    'Seroven',
    'seroven@taskia.local',
    'user',
    passwordHash,
    null,
    null,
  )
  const guardianId = await ensureUser(
    client,
    'Claudia',
    'claudia@taskia.local',
    'parent',
    passwordHash,
    null,
    null,
  )
  await client.query(
    `INSERT INTO parent_student_links (parent_id, student_id, is_active)
     VALUES ($1, $2, TRUE)
     ON CONFLICT (parent_id, student_id) DO UPDATE SET is_active = TRUE`,
    [guardianId, explorerId],
  )
  await client.query(
    `INSERT INTO parent_notify_prefs (parent_id) VALUES ($1)
     ON CONFLICT (parent_id) DO NOTHING`,
    [guardianId],
  )
  for (const name of PRIMARY_COURSES) {
    await client.query(
      `INSERT INTO courses (user_id, name, is_active)
       VALUES ($1, $2, TRUE)
       ON CONFLICT (user_id, name) DO NOTHING`,
      [explorerId, name],
    )
  }
  console.log('  demo: Seroven, Claudia y materias de primaria')
}

async function ensureCourses(client: Client, userId: number) {
  for (const name of PRIMARY_COURSES) {
    await client.query(
      `INSERT INTO courses (user_id, name, is_active)
       VALUES ($1, $2, TRUE)
       ON CONFLICT (user_id, name) DO NOTHING`,
      [userId, name],
    )
  }
}

async function ensureLink(client: Client, parentId: number, studentId: number) {
  await client.query(
    `INSERT INTO parent_student_links (parent_id, student_id, is_active)
     VALUES ($1, $2, TRUE)
     ON CONFLICT (parent_id, student_id) DO UPDATE SET is_active = TRUE`,
    [parentId, studentId],
  )
  await client.query(
    `INSERT INTO parent_notify_prefs (parent_id) VALUES ($1)
     ON CONFLICT (parent_id) DO NOTHING`,
    [parentId],
  )
}

async function ensureMembership(client: Client, troopId: number, userId: number, role: string) {
  const activeElsewhere = await client.query(
    `SELECT id, troop_id FROM troop_members
     WHERE user_id = $1 AND left_at IS NULL AND troop_id <> $2
     LIMIT 1`,
    [userId, troopId],
  )
  if (activeElsewhere.rows[0]) return

  const existing = await client.query(
    `SELECT id, left_at, role FROM troop_members
     WHERE troop_id = $1 AND user_id = $2 LIMIT 1`,
    [troopId, userId],
  )
  if (existing.rows[0]) {
    if (existing.rows[0].left_at != null) {
      await client.query(
        `UPDATE troop_members SET left_at = NULL, role = $1, joined_at = NOW() WHERE id = $2`,
        [role, existing.rows[0].id],
      )
    } else if (existing.rows[0].role !== role) {
      await client.query(`UPDATE troop_members SET role = $1 WHERE id = $2`, [
        role,
        existing.rows[0].id,
      ])
    }
    return
  }
  await client.query(
    `INSERT INTO troop_members (troop_id, user_id, role) VALUES ($1, $2, $3)`,
    [troopId, userId, role],
  )
}

async function ensureWeekAward(
  client: Client,
  userId: number,
  amount: number,
  weekStart: string,
  seedKey: number,
) {
  if (amount <= 0) return
  const sourceId = 9_000_000 + seedKey
  await client.query(
    `INSERT INTO xp_awards
       (user_id, source_type, source_id, amount, effort_score, reason, week_start)
     VALUES ($1, 'task_done_simple', $2, $3, NULL, 'seed demo tropas', $4)
     ON CONFLICT (user_id, source_type, source_id) DO UPDATE
       SET amount = EXCLUDED.amount,
           week_start = EXCLUDED.week_start,
           reason = EXCLUDED.reason`,
    [userId, sourceId, amount, weekStart],
  )
}

async function seedDemoTroops(client: Client, passwordHash: string) {
  const anchor = await client.query(
    `SELECT id FROM troops WHERE name = $1 AND is_active = TRUE LIMIT 1`,
    [ANCHOR_TROOP],
  )
  const already =
    anchor.rows[0] != null &&
    (
      await client.query(
        `SELECT COUNT(*)::int AS c FROM troop_members
         WHERE troop_id = $1 AND left_at IS NULL`,
        [Number(anchor.rows[0].id)],
      )
    ).rows[0].c >= 5

  if (already) {
    console.log(`  seed tropas demo: "${ANCHOR_TROOP}" ya tiene miembros — omito`)
    return
  }

  const weekStart = weekStartMondayLima()
  let seedKey = 1
  for (const troop of TROOPS) {
    const existingTroop = await client.query(`SELECT id FROM troops WHERE name = $1 LIMIT 1`, [
      troop.name,
    ])
    let troopId: number
    if (existingTroop.rows[0]) {
      troopId = Number(existingTroop.rows[0].id)
      await client.query(
        `UPDATE troops
         SET is_active = TRUE, planet_style_id = $2, planet_seed = $3
         WHERE id = $1`,
        [troopId, troop.planet_style_id, troop.planet_seed],
      )
    } else {
      const ins = await client.query(
        `INSERT INTO troops (name, planet_style_id, planet_seed)
         VALUES ($1, $2, $3) RETURNING id`,
        [troop.name, troop.planet_style_id, troop.planet_seed],
      )
      troopId = Number(ins.rows[0].id)
    }

    for (const member of troop.members) {
      const xpTotal = (member.level - 1) * 1000 + member.xpInto
      const explorerId = await ensureUser(
        client,
        member.username,
        `${member.username.toLowerCase()}@taskia.local`,
        'user',
        passwordHash,
        member.level,
        xpTotal,
      )
      await ensureCourses(client, explorerId)
      await ensureMembership(client, troopId, explorerId, member.role)
      await ensureWeekAward(client, explorerId, member.xpWeek, weekStart, seedKey)
      seedKey += 1

      const guardianName = GUARDIAN_BY_EXPLORER[member.username]
      if (guardianName) {
        const guardianId = await ensureUser(
          client,
          guardianName,
          `${guardianName.toLowerCase()}@taskia.local`,
          'parent',
          passwordHash,
          1,
          0,
        )
        await ensureLink(client, guardianId, explorerId)
      }
    }
  }
  console.log(`  seed tropas demo listas; password ${DEMO_PASSWORD}; week_start=${weekStart}`)
}

async function fillDerivedPlanetFields(client: Client) {
  await client.query(`
    UPDATE users
    SET avatar_preset_id = 'rocket'
    WHERE avatar_kind = 'preset' AND avatar_preset_id IS NULL
  `)
  await client.query(`
    UPDATE troops
    SET planet_seed = (id % 2147483647)::int
    WHERE planet_seed = 0
  `)
  await client.query(`
    UPDATE troops
    SET planet_config = jsonb_build_object(
      'seed', planet_style_id || ':' || planet_seed::text,
      'bodyType', CASE planet_style_id
        WHEN 'gas_teal' THEN 'gas'
        WHEN 'lava_amber' THEN 'lava'
        WHEN 'neon_violet' THEN 'candy'
        WHEN 'ice_cyan' THEN 'ice'
        WHEN 'forest_green' THEN 'forest'
        WHEN 'rose_dust' THEN 'cloud'
        WHEN 'shadow_slate' THEN 'desert'
        ELSE 'rocky'
      END
    )
    WHERE planet_config IS NULL
  `)
}

export async function up(client: Client) {
  await runScript(client, SCHEMA)
  await seedAdmin(client)
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10)
  await seedDemoUsers(client)
  await seedDemoTroops(client, passwordHash)
  await fillDerivedPlanetFields(client)
}
