-- Oleada 0: progresión (XP/nivel), log de awards, tropas e invitaciones.
-- Cupo máx. 10 miembros y límite 20 tareas/día se validan en la app (oleadas 1/3).
-- Semana y día civil de producto: America/Lima (week_start = lunes).

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS level INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS xp_total BIGINT NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_level'
  ) THEN
    ALTER TABLE users ADD CONSTRAINT ck_users_level CHECK (level >= 1);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_xp_total'
  ) THEN
    ALTER TABLE users ADD CONSTRAINT ck_users_xp_total CHECK (xp_total >= 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_users_level_xp
  ON users (level DESC, xp_total DESC);

CREATE TABLE IF NOT EXISTS xp_awards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_id BIGINT NOT NULL,
  amount INT NOT NULL,
  effort_score INT NULL,
  reason VARCHAR(200) NULL,
  week_start DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_xp_awards_source_type CHECK (
    source_type IN ('task_done_simple', 'task_study', 'mission', 'challenge')
  ),
  CONSTRAINT ck_xp_awards_amount CHECK (amount > 0),
  CONSTRAINT ck_xp_awards_effort_score CHECK (
    effort_score IS NULL OR (effort_score >= 1 AND effort_score <= 100)
  ),
  CONSTRAINT uq_xp_awards_user_source UNIQUE (user_id, source_type, source_id)
);

CREATE INDEX IF NOT EXISTS idx_xp_awards_user_week
  ON xp_awards (user_id, week_start);

CREATE INDEX IF NOT EXISTS idx_xp_awards_week
  ON xp_awards (week_start);

CREATE TABLE IF NOT EXISTS troops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_troops_active
  ON troops (id) WHERE is_active;

DROP TRIGGER IF EXISTS trg_troops_updated_at ON troops;
CREATE TRIGGER trg_troops_updated_at
  BEFORE UPDATE ON troops
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

CREATE TABLE IF NOT EXISTS troop_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  troop_id BIGINT NOT NULL REFERENCES troops (id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  left_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_troop_members_role CHECK (
    role IN ('captain', 'copilot', 'member')
  ),
  CONSTRAINT uq_troop_members_troop_user UNIQUE (troop_id, user_id)
);

-- Una sola tropa activa por explorador.
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_members_user_active
  ON troop_members (user_id) WHERE left_at IS NULL;

-- Un capitán activo por tropa.
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_members_captain_active
  ON troop_members (troop_id)
  WHERE role = 'captain' AND left_at IS NULL;

-- Un copiloto activo por tropa.
CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_members_copilot_active
  ON troop_members (troop_id)
  WHERE role = 'copilot' AND left_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_troop_members_troop_active
  ON troop_members (troop_id) WHERE left_at IS NULL;

CREATE TABLE IF NOT EXISTS troop_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  troop_id BIGINT NOT NULL REFERENCES troops (id) ON DELETE CASCADE,
  from_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  to_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  responded_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_troop_invites_status CHECK (
    status IN ('pending', 'accepted', 'rejected', 'cancelled')
  ),
  CONSTRAINT ck_troop_invites_not_self CHECK (from_user_id <> to_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_troop_invites_pending
  ON troop_invites (troop_id, to_user_id) WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_troop_invites_to_pending
  ON troop_invites (to_user_id) WHERE status = 'pending';
