import type { Client } from 'pg'

const KINDS = [
  'task_tutor',
  'mission_tutor',
  'transcribe',
  'challenge_generate',
  'challenge_grade',
  'parent_tutor',
  'planet_generate',
  'daily_summary',
  'board_intent',
  'board_facts',
] as const

export async function up(client: Client): Promise<void> {
  const list = KINDS.map((kind) => `'${kind}'`).join(', ')
  await client.query(`ALTER TABLE llm_usage DROP CONSTRAINT IF EXISTS llm_usage_kind_check`)
  await client.query(`
    ALTER TABLE llm_usage
      ADD CONSTRAINT llm_usage_kind_check CHECK (kind IN (${list}))
  `)
  await client.query(`
    CREATE TABLE IF NOT EXISTS board_gaps (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      code TEXT NOT NULL,
      gap_key VARCHAR(40) NOT NULL,
      origin TEXT NOT NULL,
      attempts INT NOT NULL DEFAULT 0
    )
  `)
  await client.query(`
    CREATE INDEX IF NOT EXISTS idx_board_gaps_key ON board_gaps (gap_key, created_at)
  `)
  await client.query(`
    ALTER TABLE study_sessions
      ADD COLUMN IF NOT EXISTS pending_board_facts TEXT
  `)
  await client.query(`
    ALTER TABLE study_mission_sessions
      ADD COLUMN IF NOT EXISTS pending_board_facts TEXT
  `)
}
